using System.Diagnostics;
namespace ssSystem_ {
public partial class ExtendedActions {
/// <summary>
/// Action: CreateEntityAttribute
/// </summary>

public static async Task<string> CreateEntityAttribute(IRequestContext requestContext,RC_2efffbee03fccc31484e893e007e6c9a inParamSource,CancellationToken cancellationToken) {
string outParamId = default;
outParamId = "";

using var entityActionActivity = activitySource.CreateEntityActionActivity("CreateEntityAttribute", "e036dc54-7115-6cde-6e3b-5024eec294d9.#CreateEntity", "System_", "478870b9-2d60-4f73-9eb3-7cd8b994a737");
ENEntityAttributeEntityRecord ssENEntityAttribute = inParamSource;
await using (var trans = await DatabaseAccess.ForRuntimeDatabase.GetRequestTransactionAsync(cancellationToken)) {
string insertSql =
"INSERT INTO " + ENEntityAttributeEntity.LocalViewName(null, null) + " (" +
" \"id\"" +
", \"name\"" +
", \"entityid\"" +
", \"datatype\"" +
", \"length\"" +
", \"decimals\"" +
", \"ismandatory\"" +
", \"isautogenerated\"" +
", \"label\"" +
", \"ordernumber\"" +
", \"foreignkeyentityid\"" +
" ) VALUES (" +
" @ssId" +
", @ssName" +
", @ssEntityId" +
", @ssDataType" +
", @ssLength" +
", @ssDecimals" +
", @ssIsMandatory" +
", @ssIsAutoGenerated" +
", @ssLabel" +
", @ssOrderNumber" +
", @ssForeignKeyEntityId" +
" )";
await using(var insertSqlCmd = trans.CreateCommand(insertSql)){
entityActionActivity.AddSqlActivityTags(insertSqlCmd.CommandText);
insertSqlCmd.CreateParameter("@ssId", DbType.String, ssENEntityAttribute.ssId);
insertSqlCmd.CreateParameter("@ssName", DbType.String, ssENEntityAttribute.ssName);
insertSqlCmd.CreateParameter("@ssEntityId", DbType.String, ssENEntityAttribute.ssEntityId);
insertSqlCmd.CreateParameter("@ssDataType", DbType.String, ssENEntityAttribute.ssDataType);
insertSqlCmd.CreateParameter("@ssLength", DbType.Int32, ssENEntityAttribute.ssLength);
insertSqlCmd.CreateParameter("@ssDecimals", DbType.Int32, ssENEntityAttribute.ssDecimals);
insertSqlCmd.CreateParameter("@ssIsMandatory", DbType.Boolean, ssENEntityAttribute.ssIsMandatory);
insertSqlCmd.CreateParameter("@ssIsAutoGenerated", DbType.Boolean, ssENEntityAttribute.ssIsAutoGenerated);
insertSqlCmd.CreateParameter("@ssLabel", DbType.String, ssENEntityAttribute.ssLabel);
insertSqlCmd.CreateParameter("@ssOrderNumber", DbType.Int32, ssENEntityAttribute.ssOrderNumber);
if ((ssENEntityAttribute.ssForeignKeyEntityId=="")) {
insertSqlCmd.CreateParameter("@ssForeignKeyEntityId", DbType.String, DBNull.Value);
} else {
insertSqlCmd.CreateParameter("@ssForeignKeyEntityId", DbType.String, ssENEntityAttribute.ssForeignKeyEntityId);

}
await insertSqlCmd.ExecuteNonQueryAsync(description: "Entity Action CreateEntityAttribute", isApplication: true, skipLog: false, applyTransformationsToParameters: false, cancellationToken: cancellationToken);
}
outParamId = ssENEntityAttribute.ssId;
}
return outParamId;
}

/// <summary>
/// Action: CreateOrUpdateEntityAttribute
/// </summary>

public static async Task<string> CreateOrUpdateEntityAttribute(IRequestContext requestContext,BitArray usedFields,RC_2efffbee03fccc31484e893e007e6c9a inParamSource,CancellationToken cancellationToken) {
string outParamId = default;
outParamId = "";

using var entityActionActivity = activitySource.CreateEntityActionActivity("CreateOrUpdateEntityAttribute", "e036dc54-7115-6cde-6e3b-5024eec294d9.#CreateOrUpdateEntity", "System_", "478870b9-2d60-4f73-9eb3-7cd8b994a737");
ENEntityAttributeEntityRecord ssENEntityAttribute = inParamSource;
await using (var trans = await DatabaseAccess.ForRuntimeDatabase.GetRequestTransactionAsync(cancellationToken)) {
if(usedFields == null){
usedFields = new BitArray(11,true);
}
string updateSet = "UPDATE " + ENEntityAttributeEntity.LocalViewName(null, BuiltInFunction.GetCurrentLocale()) + " SET ";
string parameters = "";
parameters = (usedFields[1] ? (StringUtils.SuffixIfNotEmpty(parameters, ", ") + "\"name\" = @ssName"): parameters);
parameters = (usedFields[2] ? (StringUtils.SuffixIfNotEmpty(parameters, ", ") + "\"entityid\" = @ssEntityId"): parameters);
parameters = (usedFields[3] ? (StringUtils.SuffixIfNotEmpty(parameters, ", ") + "\"datatype\" = @ssDataType"): parameters);
parameters = (usedFields[4] ? (StringUtils.SuffixIfNotEmpty(parameters, ", ") + "\"length\" = @ssLength"): parameters);
parameters = (usedFields[5] ? (StringUtils.SuffixIfNotEmpty(parameters, ", ") + "\"decimals\" = @ssDecimals"): parameters);
parameters = (usedFields[6] ? (StringUtils.SuffixIfNotEmpty(parameters, ", ") + "\"ismandatory\" = @ssIsMandatory"): parameters);
parameters = (usedFields[7] ? (StringUtils.SuffixIfNotEmpty(parameters, ", ") + "\"isautogenerated\" = @ssIsAutoGenerated"): parameters);
parameters = (usedFields[8] ? (StringUtils.SuffixIfNotEmpty(parameters, ", ") + "\"label\" = @ssLabel"): parameters);
parameters = (usedFields[9] ? (StringUtils.SuffixIfNotEmpty(parameters, ", ") + "\"ordernumber\" = @ssOrderNumber"): parameters);
parameters = (usedFields[10] ? (StringUtils.SuffixIfNotEmpty(parameters, ", ") + "\"foreignkeyentityid\" = @ssForeignKeyEntityId"): parameters);
string whereCondition = " WHERE \"id\" = @idparam_ssENEntityAttribute_ssId_";
var sql = updateSet + parameters + whereCondition;
if (string.IsNullOrEmpty(parameters)){
string dummyUpdate = "\"ismandatory\" = \"ismandatory\"";
sql = updateSet + dummyUpdate + whereCondition;
}
await using(var sqlCmd = trans.CreateCommand(sql)){
if(usedFields[1]) {
sqlCmd.CreateParameter("@ssName", DbType.String, ssENEntityAttribute.ssName);
}
if(usedFields[2]) {
sqlCmd.CreateParameter("@ssEntityId", DbType.String, ssENEntityAttribute.ssEntityId);
}
if(usedFields[3]) {
sqlCmd.CreateParameter("@ssDataType", DbType.String, ssENEntityAttribute.ssDataType);
}
if(usedFields[4]) {
sqlCmd.CreateParameter("@ssLength", DbType.Int32, ssENEntityAttribute.ssLength);
}
if(usedFields[5]) {
sqlCmd.CreateParameter("@ssDecimals", DbType.Int32, ssENEntityAttribute.ssDecimals);
}
if(usedFields[6]) {
sqlCmd.CreateParameter("@ssIsMandatory", DbType.Boolean, ssENEntityAttribute.ssIsMandatory);
}
if(usedFields[7]) {
sqlCmd.CreateParameter("@ssIsAutoGenerated", DbType.Boolean, ssENEntityAttribute.ssIsAutoGenerated);
}
if(usedFields[8]) {
sqlCmd.CreateParameter("@ssLabel", DbType.String, ssENEntityAttribute.ssLabel);
}
if(usedFields[9]) {
sqlCmd.CreateParameter("@ssOrderNumber", DbType.Int32, ssENEntityAttribute.ssOrderNumber);
}
if(usedFields[10]) {
if ((ssENEntityAttribute.ssForeignKeyEntityId=="")) {
sqlCmd.CreateParameter("@ssForeignKeyEntityId", DbType.String, DBNull.Value);
} else {
sqlCmd.CreateParameter("@ssForeignKeyEntityId", DbType.String, ssENEntityAttribute.ssForeignKeyEntityId);

}
}
sqlCmd.CreateParameter("@idparam_ssENEntityAttribute_ssId_", DbType.String, ssENEntityAttribute.ssId);
int counter = 0;
if(ssENEntityAttribute.ssId != "") {
counter = await sqlCmd.ExecuteNonQueryAsync(description: "Entity Action CreateOrUpdateEntityAttribute (update)", isApplication: true, skipLog: false, applyTransformationsToParameters: false, cancellationToken: cancellationToken);
}
if( counter == 0) {
string insertSql =
"INSERT INTO " + ENEntityAttributeEntity.LocalViewName(null, null) + " (" +
" \"id\"" +
", \"name\"" +
", \"entityid\"" +
", \"datatype\"" +
", \"length\"" +
", \"decimals\"" +
", \"ismandatory\"" +
", \"isautogenerated\"" +
", \"label\"" +
", \"ordernumber\"" +
", \"foreignkeyentityid\"" +
" ) VALUES (" +
" @ssId" +
", @ssName" +
", @ssEntityId" +
", @ssDataType" +
", @ssLength" +
", @ssDecimals" +
", @ssIsMandatory" +
", @ssIsAutoGenerated" +
", @ssLabel" +
", @ssOrderNumber" +
", @ssForeignKeyEntityId" +
" )";
await using(var insertSqlCmd = trans.CreateCommand(insertSql)){
entityActionActivity.AddSqlActivityTags(insertSqlCmd.CommandText);
insertSqlCmd.CreateParameter("@ssId", DbType.String, ssENEntityAttribute.ssId);
insertSqlCmd.CreateParameter("@ssName", DbType.String, ssENEntityAttribute.ssName);
insertSqlCmd.CreateParameter("@ssEntityId", DbType.String, ssENEntityAttribute.ssEntityId);
insertSqlCmd.CreateParameter("@ssDataType", DbType.String, ssENEntityAttribute.ssDataType);
insertSqlCmd.CreateParameter("@ssLength", DbType.Int32, ssENEntityAttribute.ssLength);
insertSqlCmd.CreateParameter("@ssDecimals", DbType.Int32, ssENEntityAttribute.ssDecimals);
insertSqlCmd.CreateParameter("@ssIsMandatory", DbType.Boolean, ssENEntityAttribute.ssIsMandatory);
insertSqlCmd.CreateParameter("@ssIsAutoGenerated", DbType.Boolean, ssENEntityAttribute.ssIsAutoGenerated);
insertSqlCmd.CreateParameter("@ssLabel", DbType.String, ssENEntityAttribute.ssLabel);
insertSqlCmd.CreateParameter("@ssOrderNumber", DbType.Int32, ssENEntityAttribute.ssOrderNumber);
if ((ssENEntityAttribute.ssForeignKeyEntityId=="")) {
insertSqlCmd.CreateParameter("@ssForeignKeyEntityId", DbType.String, DBNull.Value);
} else {
insertSqlCmd.CreateParameter("@ssForeignKeyEntityId", DbType.String, ssENEntityAttribute.ssForeignKeyEntityId);

}
await insertSqlCmd.ExecuteNonQueryAsync(description: "Entity Action CreateOrUpdateEntityAttribute", isApplication: true, skipLog: false, applyTransformationsToParameters: false, cancellationToken: cancellationToken);
}
outParamId = ssENEntityAttribute.ssId;
} else {
entityActionActivity.AddSqlActivityTags(sqlCmd.CommandText);
outParamId = ssENEntityAttribute.ssId;
}
}
}
return outParamId;
}

/// <summary>
/// Action: CreateOrUpdateSomeEntityAttribute
/// </summary>

public static async Task CreateOrUpdateSomeEntityAttribute(IRequestContext requestContext,RL_582b59adcb0660dd0915958cbaffea77 inParamSourceList,CancellationToken cancellationToken) {
using var entityActionActivity = activitySource.CreateEntityActionActivity("CreateOrUpdateSomeEntityAttribute", "e036dc54-7115-6cde-6e3b-5024eec294d9.#CreateOrUpdateAllEntity", "System_", "478870b9-2d60-4f73-9eb3-7cd8b994a737");
string entityTableName = ENEntityAttributeEntity.LocalViewName(null, null);
string insertSql ="INSERT INTO " + entityTableName + " (\"id\", \"name\", \"entityid\", \"datatype\", \"length\", \"decimals\", \"ismandatory\", \"isautogenerated\", \"label\", \"ordernumber\", \"foreignkeyentityid\") VALUES ( unnest(@ssId),  unnest(@ssName),  unnest(@ssEntityId),  unnest(@ssDataType),  unnest(@ssLength),  unnest(@ssDecimals),  unnest(@ssIsMandatory),  unnest(@ssIsAutoGenerated),  unnest(@ssLabel),  unnest(@ssOrderNumber),  unnest(@ssForeignKeyEntityId)) ON CONFLICT(\"id\") do update set \"name\" = EXCLUDED.\"name\", \"entityid\" = EXCLUDED.\"entityid\", \"datatype\" = EXCLUDED.\"datatype\", \"length\" = EXCLUDED.\"length\", \"decimals\" = EXCLUDED.\"decimals\", \"ismandatory\" = EXCLUDED.\"ismandatory\", \"isautogenerated\" = EXCLUDED.\"isautogenerated\", \"label\" = EXCLUDED.\"label\", \"ordernumber\" = EXCLUDED.\"ordernumber\", \"foreignkeyentityid\" = EXCLUDED.\"foreignkeyentityid\" ";
insertSql+= "";


List<string> insertIdList = new List<string>();
List<string> insertNameList = new List<string>();
List<object> insertEntityIdList = new List<object>();
List<string> insertDataTypeList = new List<string>();
List<int> insertLengthList = new List<int>();
List<int> insertDecimalsList = new List<int>();
List<bool> insertIsMandatoryList = new List<bool>();
List<bool> insertIsAutoGeneratedList = new List<bool>();
List<string> insertLabelList = new List<string>();
List<int> insertOrderNumberList = new List<int>();
List<object> insertForeignKeyEntityIdList = new List<object>();


var executionService = DatabaseAccess.ForRuntimeDatabase.DatabaseServices.ExecutionService;
inParamSourceList.StartIteration();
try {
while (!inParamSourceList.Eof) {
var record = ((RC_2efffbee03fccc31484e893e007e6c9a)inParamSourceList.Current).ssENEntityAttribute;
insertIdList.Add((string)executionService.TransformRuntimeToDatabaseValue(DbType.String, record.ssId));
insertNameList.Add((string)executionService.TransformRuntimeToDatabaseValue(DbType.String, record.ssName));
insertEntityIdList.Add((string)executionService.TransformRuntimeToDatabaseValue(DbType.String, record.ssEntityId));
insertDataTypeList.Add((string)executionService.TransformRuntimeToDatabaseValue(DbType.String, record.ssDataType));
insertLengthList.Add((int)executionService.TransformRuntimeToDatabaseValue(DbType.Int32, record.ssLength));
insertDecimalsList.Add((int)executionService.TransformRuntimeToDatabaseValue(DbType.Int32, record.ssDecimals));
insertIsMandatoryList.Add((bool)executionService.TransformRuntimeToDatabaseValue(DbType.Boolean, record.ssIsMandatory));
insertIsAutoGeneratedList.Add((bool)executionService.TransformRuntimeToDatabaseValue(DbType.Boolean, record.ssIsAutoGenerated));
insertLabelList.Add((string)executionService.TransformRuntimeToDatabaseValue(DbType.String, record.ssLabel));
insertOrderNumberList.Add((int)executionService.TransformRuntimeToDatabaseValue(DbType.Int32, record.ssOrderNumber));
if ((record.ssForeignKeyEntityId=="")) {
insertForeignKeyEntityIdList.Add(null);
} else {
insertForeignKeyEntityIdList.Add((string)executionService.TransformRuntimeToDatabaseValue(DbType.String, record.ssForeignKeyEntityId));
}
inParamSourceList.Advance();
} } finally {
inParamSourceList.EndIteration(); }
var finalSqlBuilder = new StringBuilder();
await using (var trans = await DatabaseAccess.ForRuntimeDatabase.GetRequestTransactionAsync(cancellationToken)) {
if (!insertIdList.IsEmpty() || !insertNameList.IsEmpty() || !insertEntityIdList.IsEmpty() || !insertDataTypeList.IsEmpty() || !insertLengthList.IsEmpty() || !insertDecimalsList.IsEmpty() || !insertIsMandatoryList.IsEmpty() || !insertIsAutoGeneratedList.IsEmpty() || !insertLabelList.IsEmpty() || !insertOrderNumberList.IsEmpty() || !insertForeignKeyEntityIdList.IsEmpty()){
await using(var insertSqlCmd = trans.CreateCommand(insertSql)){
executionService.CreateParameter(insertSqlCmd,"@ssId",DbType.String,insertIdList);
executionService.CreateParameter(insertSqlCmd,"@ssName",DbType.String,insertNameList);
executionService.CreateParameter(insertSqlCmd,"@ssEntityId",DbType.String,insertEntityIdList);
executionService.CreateParameter(insertSqlCmd,"@ssDataType",DbType.String,insertDataTypeList);
executionService.CreateParameter(insertSqlCmd,"@ssLength",DbType.Int32,insertLengthList);
executionService.CreateParameter(insertSqlCmd,"@ssDecimals",DbType.Int32,insertDecimalsList);
executionService.CreateParameter(insertSqlCmd,"@ssIsMandatory",DbType.Boolean,insertIsMandatoryList);
executionService.CreateParameter(insertSqlCmd,"@ssIsAutoGenerated",DbType.Boolean,insertIsAutoGeneratedList);
executionService.CreateParameter(insertSqlCmd,"@ssLabel",DbType.String,insertLabelList);
executionService.CreateParameter(insertSqlCmd,"@ssOrderNumber",DbType.Int32,insertOrderNumberList);
executionService.CreateParameter(insertSqlCmd,"@ssForeignKeyEntityId",DbType.String,insertForeignKeyEntityIdList);
await insertSqlCmd.PrepareAsync(cancellationToken);
await insertSqlCmd.ExecuteNonQueryAsync(description: "Entity Action CreateOrUpdateSomeEntityAttribute (insert)", isApplication: true, skipLog: false, applyTransformationsToParameters: false, cancellationToken: cancellationToken);
finalSqlBuilder.Append(insertSqlCmd.CommandText);
}
}
}
entityActionActivity.AddSqlActivityTags(finalSqlBuilder.ToString());
return;
}

/// <summary>
/// Action: DeleteEntityAttribute
/// </summary>

public static async Task DeleteEntityAttribute(IRequestContext requestContext,string inParamId,CancellationToken cancellationToken) {
using var entityActionActivity = activitySource.CreateEntityActionActivity("DeleteEntityAttribute", "e036dc54-7115-6cde-6e3b-5024eec294d9.#DeleteEntity", "System_", "478870b9-2d60-4f73-9eb3-7cd8b994a737");
await using (var trans = await DatabaseAccess.ForRuntimeDatabase.GetRequestTransactionAsync(cancellationToken)) {
string sql =
"DELETE " +
"FROM " + ENEntityAttributeEntity.LocalViewName(null, BuiltInFunction.GetCurrentLocale()) + " " +
"WHERE \"id\" = @inParamId";
await using(var sqlCmd = trans.CreateCommand(sql)){
entityActionActivity.AddSqlActivityTags(sqlCmd.CommandText);
sqlCmd.CreateParameter("@inParamId", DbType.String, inParamId);
await sqlCmd.ExecuteNonQueryAsync(description: "Entity Action DeleteEntityAttribute", isApplication: true, skipLog: false, applyTransformationsToParameters: false, cancellationToken: cancellationToken);
}
}
return;
}

/// <summary>
/// Action: GetEntityAttribute
/// </summary>

public static async Task<RC_2efffbee03fccc31484e893e007e6c9a> GetEntityAttribute(IRequestContext requestContext,string inParamId,CancellationToken cancellationToken) {
RC_2efffbee03fccc31484e893e007e6c9a outParamRecord = default;
outParamRecord = new RC_2efffbee03fccc31484e893e007e6c9a();

using var entityActionActivity = activitySource.CreateEntityActionActivity("GetEntityAttribute", "e036dc54-7115-6cde-6e3b-5024eec294d9.#GetEntity", "System_", "478870b9-2d60-4f73-9eb3-7cd8b994a737");
await using (var trans = await DatabaseAccess.ForRuntimeDatabase.GetReadOnlyTransactionAsync(cancellationToken)) {
string sql =
"SELECT " +
" \"id\"" +
", \"name\"" +
", \"entityid\"" +
", \"datatype\"" +
", \"length\"" +
", \"decimals\"" +
", \"ismandatory\"" +
", \"isautogenerated\"" +
", \"label\"" +
", \"ordernumber\"" +
", \"foreignkeyentityid\"" +
" FROM " + ENEntityAttributeEntity.LocalViewName(null, BuiltInFunction.GetCurrentLocale()) + " " +
"WHERE \"id\" = @inParamId";
await using(var sqlCmd = trans.CreateCommand(sql)){
entityActionActivity.AddSqlActivityTags(sqlCmd.CommandText);
sqlCmd.CreateParameter("@inParamId", DbType.String, inParamId);
await using (var reader = await sqlCmd.ExecuteReaderAsync(description: "Entity Action GetEntityAttribute", isApplication: true, skipLog: false, applyTransformationsToParameters: false, cancellationToken: cancellationToken)) {
if (await reader.ReadAsync(cancellationToken)){
outParamRecord.ReadDB(reader);
outParamRecord.AllOptimizedAttributes = new BitArray[] { new BitArray(11,false) };
} else {
throw DatabaseErrorsHelper.EntityRecordNotFound(ENEntityAttributeEntity.LocalViewName(null, BuiltInFunction.GetCurrentLocale()), "inParamId");
 }
}
}
}
return outParamRecord;
}

/// <summary>
/// Action: GetEntityAttributeForUpdate
/// </summary>

public static async Task<RC_2efffbee03fccc31484e893e007e6c9a> GetEntityAttributeForUpdate(IRequestContext requestContext,string inParamId,CancellationToken cancellationToken) {
RC_2efffbee03fccc31484e893e007e6c9a outParamRecord = default;
outParamRecord = new RC_2efffbee03fccc31484e893e007e6c9a();

using var entityActionActivity = activitySource.CreateEntityActionActivity("GetEntityAttributeForUpdate", "e036dc54-7115-6cde-6e3b-5024eec294d9.#GetEntityForUpdate", "System_", "478870b9-2d60-4f73-9eb3-7cd8b994a737");
await using (var trans = await DatabaseAccess.ForRuntimeDatabase.GetRequestTransactionAsync(cancellationToken)) {
string sql =
"SELECT " +
" \"id\"" +
", \"name\"" +
", \"entityid\"" +
", \"datatype\"" +
", \"length\"" +
", \"decimals\"" +
", \"ismandatory\"" +
", \"isautogenerated\"" +
", \"label\"" +
", \"ordernumber\"" +
", \"foreignkeyentityid\"" +
"FROM " + ENEntityAttributeEntity.LocalViewName(null, BuiltInFunction.GetCurrentLocale()) + " " +
"WHERE \"id\" = @inParamId  FOR UPDATE";
await using(var sqlCmd = trans.CreateCommand(sql)){
entityActionActivity.AddSqlActivityTags(sqlCmd.CommandText);
sqlCmd.CreateParameter("@inParamId", DbType.String, inParamId);
await using (var reader = await sqlCmd.ExecuteReaderAsync(description: "Entity Action GetEntityAttributeForUpdate", isApplication: true, skipLog: false, applyTransformationsToParameters: false, cancellationToken: cancellationToken)) {
if (await reader.ReadAsync(cancellationToken)){
outParamRecord.ReadDB(reader);
outParamRecord.AllOptimizedAttributes = new BitArray[] { new BitArray(11,false) };
} else {
throw DatabaseErrorsHelper.EntityRecordNotFound(ENEntityAttributeEntity.LocalViewName(null, BuiltInFunction.GetCurrentLocale()), "inParamId");
 }
}
}
}
return outParamRecord;
}

/// <summary>
/// Action: UpdateEntityAttribute
/// </summary>

public static async Task UpdateEntityAttribute(IRequestContext requestContext,BitArray usedFields,RC_2efffbee03fccc31484e893e007e6c9a inParamSource,CancellationToken cancellationToken) {
using var entityActionActivity = activitySource.CreateEntityActionActivity("UpdateEntityAttribute", "e036dc54-7115-6cde-6e3b-5024eec294d9.#UpdateEntity", "System_", "478870b9-2d60-4f73-9eb3-7cd8b994a737");
ENEntityAttributeEntityRecord ssENEntityAttribute = inParamSource;
await using (var trans = await DatabaseAccess.ForRuntimeDatabase.GetRequestTransactionAsync(cancellationToken)) {
if(usedFields == null){
usedFields = new BitArray(11,true);
}
string updateSet = "UPDATE " + ENEntityAttributeEntity.LocalViewName(null, BuiltInFunction.GetCurrentLocale()) + " SET ";
string parameters = "";
parameters = (usedFields[1] ? (StringUtils.SuffixIfNotEmpty(parameters, ", ") + "\"name\" = @ssName"): parameters);
parameters = (usedFields[2] ? (StringUtils.SuffixIfNotEmpty(parameters, ", ") + "\"entityid\" = @ssEntityId"): parameters);
parameters = (usedFields[3] ? (StringUtils.SuffixIfNotEmpty(parameters, ", ") + "\"datatype\" = @ssDataType"): parameters);
parameters = (usedFields[4] ? (StringUtils.SuffixIfNotEmpty(parameters, ", ") + "\"length\" = @ssLength"): parameters);
parameters = (usedFields[5] ? (StringUtils.SuffixIfNotEmpty(parameters, ", ") + "\"decimals\" = @ssDecimals"): parameters);
parameters = (usedFields[6] ? (StringUtils.SuffixIfNotEmpty(parameters, ", ") + "\"ismandatory\" = @ssIsMandatory"): parameters);
parameters = (usedFields[7] ? (StringUtils.SuffixIfNotEmpty(parameters, ", ") + "\"isautogenerated\" = @ssIsAutoGenerated"): parameters);
parameters = (usedFields[8] ? (StringUtils.SuffixIfNotEmpty(parameters, ", ") + "\"label\" = @ssLabel"): parameters);
parameters = (usedFields[9] ? (StringUtils.SuffixIfNotEmpty(parameters, ", ") + "\"ordernumber\" = @ssOrderNumber"): parameters);
parameters = (usedFields[10] ? (StringUtils.SuffixIfNotEmpty(parameters, ", ") + "\"foreignkeyentityid\" = @ssForeignKeyEntityId"): parameters);
string whereCondition = " WHERE \"id\" = @idparam_ssENEntityAttribute_ssId_";
var sql = updateSet + parameters + whereCondition;
if (string.IsNullOrEmpty(parameters)){
string dummyUpdate = "\"ismandatory\" = \"ismandatory\"";
sql = updateSet + dummyUpdate + whereCondition;
}
await using(var sqlCmd = trans.CreateCommand(sql)){
if(usedFields[1]) {
sqlCmd.CreateParameter("@ssName", DbType.String, ssENEntityAttribute.ssName);
}
if(usedFields[2]) {
sqlCmd.CreateParameter("@ssEntityId", DbType.String, ssENEntityAttribute.ssEntityId);
}
if(usedFields[3]) {
sqlCmd.CreateParameter("@ssDataType", DbType.String, ssENEntityAttribute.ssDataType);
}
if(usedFields[4]) {
sqlCmd.CreateParameter("@ssLength", DbType.Int32, ssENEntityAttribute.ssLength);
}
if(usedFields[5]) {
sqlCmd.CreateParameter("@ssDecimals", DbType.Int32, ssENEntityAttribute.ssDecimals);
}
if(usedFields[6]) {
sqlCmd.CreateParameter("@ssIsMandatory", DbType.Boolean, ssENEntityAttribute.ssIsMandatory);
}
if(usedFields[7]) {
sqlCmd.CreateParameter("@ssIsAutoGenerated", DbType.Boolean, ssENEntityAttribute.ssIsAutoGenerated);
}
if(usedFields[8]) {
sqlCmd.CreateParameter("@ssLabel", DbType.String, ssENEntityAttribute.ssLabel);
}
if(usedFields[9]) {
sqlCmd.CreateParameter("@ssOrderNumber", DbType.Int32, ssENEntityAttribute.ssOrderNumber);
}
if(usedFields[10]) {
if ((ssENEntityAttribute.ssForeignKeyEntityId=="")) {
sqlCmd.CreateParameter("@ssForeignKeyEntityId", DbType.String, DBNull.Value);
} else {
sqlCmd.CreateParameter("@ssForeignKeyEntityId", DbType.String, ssENEntityAttribute.ssForeignKeyEntityId);

}
}
sqlCmd.CreateParameter("@idparam_ssENEntityAttribute_ssId_", DbType.String, ssENEntityAttribute.ssId);
entityActionActivity.AddSqlActivityTags(sqlCmd.CommandText);
if (await sqlCmd.ExecuteNonQueryAsync(description: "Entity Action UpdateEntityAttribute", isApplication: true, skipLog: false, applyTransformationsToParameters: false, cancellationToken: cancellationToken) <= 0) {
throw DatabaseErrorsHelper.EntityRecordNotUpdated("EntityAttribute", ssENEntityAttribute.ssId.ToString()); }}
}
return;
}

}
}
