using System.Diagnostics;
namespace ssSystem_ {

/// <summary>
/// [Entity] EntityAttribute (VNw24BVx3mxuO1Ak7sKU2Q) <code>ENEntityAttributeEntityRecord</code> that
///  represents <code>EntityAttribute</code> <p>Description: Attributes for each entity defined i
/// n Service Studio. Old attributes are kept as inactive.</p>
/// </summary>
[OutSystems.HubEdition.RuntimePlatform.MetaInformation.EntityRecordDetails("EntityAttribute","VNw24BVx3mxuO1Ak7sKU2Q","uXCIR2Atc0+es3zYuZSnNw", 0,"", null, false)]
// Name: EntityAttribute
public partial struct ENEntityAttributeEntityRecord : ITypedRecord<ENEntityAttributeEntityRecord> {
internal static readonly GlobalObjectKey IdId = GlobalObjectKey.Parse("uXCIR2Atc0+es3zYuZSnNw*T9tGom6kKEd4B1RqmaZOBQ");
internal static readonly GlobalObjectKey IdName = GlobalObjectKey.Parse("uXCIR2Atc0+es3zYuZSnNw*bJSoSA5DMVPKdPFsCSxEGw");
internal static readonly GlobalObjectKey IdEntityId = GlobalObjectKey.Parse("uXCIR2Atc0+es3zYuZSnNw*ard6pWixukxjRGdYOJ6Fqw");
internal static readonly GlobalObjectKey IdDataType = GlobalObjectKey.Parse("uXCIR2Atc0+es3zYuZSnNw*VSIynlsCaS+CybsR15OzJg");
internal static readonly GlobalObjectKey IdLength = GlobalObjectKey.Parse("uXCIR2Atc0+es3zYuZSnNw*DivcKJnsD1Oel422wFj22w");
internal static readonly GlobalObjectKey IdDecimals = GlobalObjectKey.Parse("uXCIR2Atc0+es3zYuZSnNw*K3_X7VWkAJZrJPKFhzf4Iw");
internal static readonly GlobalObjectKey IdIsMandatory = GlobalObjectKey.Parse("uXCIR2Atc0+es3zYuZSnNw*lg+mZxLduUUQ+rpWa5EJOw");
internal static readonly GlobalObjectKey IdIsAutoGenerated = GlobalObjectKey.Parse("uXCIR2Atc0+es3zYuZSnNw*74qYpzhvpPwXcwCroUuhWA");
internal static readonly GlobalObjectKey IdLabel = GlobalObjectKey.Parse("uXCIR2Atc0+es3zYuZSnNw*DA9rf8VapnvIrM5EQhh+Ew");
internal static readonly GlobalObjectKey IdOrderNumber = GlobalObjectKey.Parse("uXCIR2Atc0+es3zYuZSnNw*nthIUdxB7YgXlV9p7MZriw");
internal static readonly GlobalObjectKey IdForeignKeyEntityId = GlobalObjectKey.Parse("uXCIR2Atc0+es3zYuZSnNw*lkOuafw5CkadLBnz+sqpDA");

public static void EnsureInitialized(){}
[OutSystems.HubEdition.RuntimePlatform.MetaInformation.EntityAttributeDetails("ID",100,false,true,false,true)]
[System.Xml.Serialization.XmlElement("Id")]
private string _ssId;
public string ssId{
  get{
      return _ssId;
  }
  set{
      if((_ssId!=value) || OptimizedAttributes[0]){
          ChangedAttributes = new BitArray(11,true);
          _ssId = value;
      }
  }
}

[OutSystems.HubEdition.RuntimePlatform.MetaInformation.EntityAttributeDetails("NAME",50,false,false,false,true)]
[System.Xml.Serialization.XmlElement("Name")]
private string _ssName;
public string ssName{
  get{
      return _ssName;
  }
  set{
      if((_ssName!=value) || OptimizedAttributes[1]){
          ChangedAttributes[1] = true;
          _ssName = value;
      }
  }
}

[OutSystems.HubEdition.RuntimePlatform.MetaInformation.EntityAttributeDetails("ENTITYID",0,false,false,true,true)]
[System.Xml.Serialization.XmlElement("EntityId")]
private string _ssEntityId;
public string ssEntityId{
  get{
      return _ssEntityId;
  }
  set{
      if((_ssEntityId!=value) || OptimizedAttributes[2]){
          ChangedAttributes[2] = true;
          _ssEntityId = value;
      }
  }
}

[OutSystems.HubEdition.RuntimePlatform.MetaInformation.EntityAttributeDetails("DATATYPE",200,false,false,false,true)]
[System.Xml.Serialization.XmlElement("DataType")]
private string _ssDataType;
public string ssDataType{
  get{
      return _ssDataType;
  }
  set{
      if((_ssDataType!=value) || OptimizedAttributes[3]){
          ChangedAttributes[3] = true;
          _ssDataType = value;
      }
  }
}

[OutSystems.HubEdition.RuntimePlatform.MetaInformation.EntityAttributeDetails("LENGTH",0,false,false,false,false)]
[System.Xml.Serialization.XmlElement("Length")]
private int _ssLength;
public int ssLength{
  get{
      return _ssLength;
  }
  set{
      if((_ssLength!=value) || OptimizedAttributes[4]){
          ChangedAttributes[4] = true;
          _ssLength = value;
      }
  }
}

[OutSystems.HubEdition.RuntimePlatform.MetaInformation.EntityAttributeDetails("DECIMALS",0,false,false,false,false)]
[System.Xml.Serialization.XmlElement("Decimals")]
private int _ssDecimals;
public int ssDecimals{
  get{
      return _ssDecimals;
  }
  set{
      if((_ssDecimals!=value) || OptimizedAttributes[5]){
          ChangedAttributes[5] = true;
          _ssDecimals = value;
      }
  }
}

[OutSystems.HubEdition.RuntimePlatform.MetaInformation.EntityAttributeDetails("ISMANDATORY",0,false,false,false,true)]
[System.Xml.Serialization.XmlElement("IsMandatory")]
private bool _ssIsMandatory;
public bool ssIsMandatory{
  get{
      return _ssIsMandatory;
  }
  set{
      if((_ssIsMandatory!=value) || OptimizedAttributes[6]){
          ChangedAttributes[6] = true;
          _ssIsMandatory = value;
      }
  }
}

[OutSystems.HubEdition.RuntimePlatform.MetaInformation.EntityAttributeDetails("ISAUTOGENERATED",0,false,false,false,true)]
[System.Xml.Serialization.XmlElement("IsAutoGenerated")]
private bool _ssIsAutoGenerated;
public bool ssIsAutoGenerated{
  get{
      return _ssIsAutoGenerated;
  }
  set{
      if((_ssIsAutoGenerated!=value) || OptimizedAttributes[7]){
          ChangedAttributes[7] = true;
          _ssIsAutoGenerated = value;
      }
  }
}

[OutSystems.HubEdition.RuntimePlatform.MetaInformation.EntityAttributeDetails("LABEL",50,false,false,false,true)]
[System.Xml.Serialization.XmlElement("Label")]
private string _ssLabel;
public string ssLabel{
  get{
      return _ssLabel;
  }
  set{
      if((_ssLabel!=value) || OptimizedAttributes[8]){
          ChangedAttributes[8] = true;
          _ssLabel = value;
      }
  }
}

[OutSystems.HubEdition.RuntimePlatform.MetaInformation.EntityAttributeDetails("ORDERNUMBER",0,false,false,false,true)]
[System.Xml.Serialization.XmlElement("OrderNumber")]
private int _ssOrderNumber;
public int ssOrderNumber{
  get{
      return _ssOrderNumber;
  }
  set{
      if((_ssOrderNumber!=value) || OptimizedAttributes[9]){
          ChangedAttributes[9] = true;
          _ssOrderNumber = value;
      }
  }
}

[OutSystems.HubEdition.RuntimePlatform.MetaInformation.EntityAttributeDetails("FOREIGNKEYENTITYID",0,false,false,true,false)]
[System.Xml.Serialization.XmlElement("ForeignKeyEntityId")]
private string _ssForeignKeyEntityId;
public string ssForeignKeyEntityId{
  get{
      return _ssForeignKeyEntityId;
  }
  set{
      if((_ssForeignKeyEntityId!=value) || OptimizedAttributes[10]){
          ChangedAttributes[10] = true;
          _ssForeignKeyEntityId = value;
      }
  }
}


public BitArray ChangedAttributes;

public BitArray OptimizedAttributes;

public ENEntityAttributeEntityRecord() {
ChangedAttributes = new BitArray(11,true);
OptimizedAttributes = new BitArray(11,false);
_ssId = "";
_ssName = "";
_ssEntityId = "";
_ssDataType = "";
_ssLength = 0;
_ssDecimals = 0;
_ssIsMandatory = false;
_ssIsAutoGenerated = false;
_ssLabel = "";
_ssOrderNumber = 0;
_ssForeignKeyEntityId = "";
}

public BitArray[] GetDefaultOptimizedValues(){
    BitArray[] all = new BitArray[0];
    return all;
}

public BitArray[] AllOptimizedAttributes{
set{
    if(value == null){
    }else{
    }
}
get{
    BitArray[] all = new BitArray[0];
    return all;
}
}

/// <summary>
/// Read a record from database
/// </summary>
/// <param name="r"> Data base reader</param>
/// <param name="index"> index</param>
public void Read( DbDataReader r, ref int index) {
ssId = r.ReadText(index++, "EntityAttribute.Id", "");
ssName = r.ReadText(index++, "EntityAttribute.Name", "");
ssEntityId = r.ReadEntityReferenceText(index++, "EntityAttribute.EntityId", "");
ssDataType = r.ReadText(index++, "EntityAttribute.DataType", "");
ssLength = r.ReadInteger(index++, "EntityAttribute.Length", 0);
ssDecimals = r.ReadInteger(index++, "EntityAttribute.Decimals", 0);
ssIsMandatory = r.ReadBoolean(index++, "EntityAttribute.IsMandatory", false);
ssIsAutoGenerated = r.ReadBoolean(index++, "EntityAttribute.IsAutoGenerated", false);
ssLabel = r.ReadText(index++, "EntityAttribute.Label", "");
ssOrderNumber = r.ReadInteger(index++, "EntityAttribute.OrderNumber", 0);
ssForeignKeyEntityId = r.ReadEntityReferenceText(index++, "EntityAttribute.ForeignKeyEntityId", "");
ChangedAttributes = new BitArray(11,false);
OptimizedAttributes = new BitArray(11,false);
}
/// <summary>
/// Read from database
/// </summary>
/// <param name="r"> Data reader</param>
public void ReadDB( DbDataReader r) {
int index = 0;
Read(r, ref index);
}

/// <summary>
/// Read from record
/// </summary>
/// <param name="r"> Record</param>
public void ReadIM(ENEntityAttributeEntityRecord r) {
this = r;
}


public static bool operator == (ENEntityAttributeEntityRecord a, ENEntityAttributeEntityRecord b) {
if (a.ssId != b.ssId) return false;
if (a.ssName != b.ssName) return false;
if (a.ssEntityId != b.ssEntityId) return false;
if (a.ssDataType != b.ssDataType) return false;
if (a.ssLength != b.ssLength) return false;
if (a.ssDecimals != b.ssDecimals) return false;
if (a.ssIsMandatory != b.ssIsMandatory) return false;
if (a.ssIsAutoGenerated != b.ssIsAutoGenerated) return false;
if (a.ssLabel != b.ssLabel) return false;
if (a.ssOrderNumber != b.ssOrderNumber) return false;
if (a.ssForeignKeyEntityId != b.ssForeignKeyEntityId) return false;
return true;
}

public static bool operator != (ENEntityAttributeEntityRecord a, ENEntityAttributeEntityRecord b) {
return !(a==b);
}

public override bool Equals(object o) {
if (o.GetType() != typeof (ENEntityAttributeEntityRecord)) return false;
return (this == (ENEntityAttributeEntityRecord)o);
}

public override int GetHashCode() {
try {
return base.GetHashCode()
 ^ ssId.GetHashCode()
 ^ ssName.GetHashCode()
 ^ ssEntityId.GetHashCode()
 ^ ssDataType.GetHashCode()
 ^ ssLength.GetHashCode()
 ^ ssDecimals.GetHashCode()
 ^ ssIsMandatory.GetHashCode()
 ^ ssIsAutoGenerated.GetHashCode()
 ^ ssLabel.GetHashCode()
 ^ ssOrderNumber.GetHashCode()
 ^ ssForeignKeyEntityId.GetHashCode()
;
} catch {
return base.GetHashCode();
}
}

public void RecursiveReset() {
}

public void InternalRecursiveSave() {
}


public ENEntityAttributeEntityRecord Duplicate() {
ENEntityAttributeEntityRecord t;
t._ssId = this._ssId;
t._ssName = this._ssName;
t._ssEntityId = this._ssEntityId;
t._ssDataType = this._ssDataType;
t._ssLength = this._ssLength;
t._ssDecimals = this._ssDecimals;
t._ssIsMandatory = this._ssIsMandatory;
t._ssIsAutoGenerated = this._ssIsAutoGenerated;
t._ssLabel = this._ssLabel;
t._ssOrderNumber = this._ssOrderNumber;
t._ssForeignKeyEntityId = this._ssForeignKeyEntityId;
t.ChangedAttributes = new BitArray(11);
t.OptimizedAttributes = new BitArray(11);
for(int i = 0; i < 11; i++){
  t.ChangedAttributes[i] = ChangedAttributes[i];
  t.OptimizedAttributes[i] = OptimizedAttributes[i];
}
return t;
}

IRecord IRecord.Duplicate() {
return Duplicate();
}

public void ToXml(Object parent, System.Xml.XmlElement baseElem, String fieldName, int detailLevel) {
throw new System.InvalidOperationException();
}

public void EvaluateFields(VarValue variable, Object parent, String baseName, String fields) {
String head = VarValue.GetHead(fields);
String tail = VarValue.GetTail(fields);
variable.Found = false;
if (head == "id") {
if (!VarValue.FieldIsOptimized(parent, baseName + ".Id")) variable.Value = ssId; else variable.Optimized = true;
} else if (head == "name") {
if (!VarValue.FieldIsOptimized(parent, baseName + ".Name")) variable.Value = ssName; else variable.Optimized = true;
} else if (head == "entityid") {
if (!VarValue.FieldIsOptimized(parent, baseName + ".EntityId")) variable.Value = ssEntityId; else variable.Optimized = true;
} else if (head == "datatype") {
if (!VarValue.FieldIsOptimized(parent, baseName + ".DataType")) variable.Value = ssDataType; else variable.Optimized = true;
} else if (head == "length") {
if (!VarValue.FieldIsOptimized(parent, baseName + ".Length")) variable.Value = ssLength; else variable.Optimized = true;
} else if (head == "decimals") {
if (!VarValue.FieldIsOptimized(parent, baseName + ".Decimals")) variable.Value = ssDecimals; else variable.Optimized = true;
} else if (head == "ismandatory") {
if (!VarValue.FieldIsOptimized(parent, baseName + ".IsMandatory")) variable.Value = ssIsMandatory; else variable.Optimized = true;
} else if (head == "isautogenerated") {
if (!VarValue.FieldIsOptimized(parent, baseName + ".IsAutoGenerated")) variable.Value = ssIsAutoGenerated; else variable.Optimized = true;
} else if (head == "label") {
if (!VarValue.FieldIsOptimized(parent, baseName + ".Label")) variable.Value = ssLabel; else variable.Optimized = true;
} else if (head == "ordernumber") {
if (!VarValue.FieldIsOptimized(parent, baseName + ".OrderNumber")) variable.Value = ssOrderNumber; else variable.Optimized = true;
} else if (head == "foreignkeyentityid") {
if (!VarValue.FieldIsOptimized(parent, baseName + ".ForeignKeyEntityId")) variable.Value = ssForeignKeyEntityId; else variable.Optimized = true;
}
if (variable.Found && tail != null) variable.EvaluateFields(this, head, tail);
}

public bool ChangedAttributeGet(GlobalObjectKey key) {
if (key.Equals(IdId)) {
return ChangedAttributes[0];
}
if (key.Equals(IdName)) {
return ChangedAttributes[1];
}
if (key.Equals(IdEntityId)) {
return ChangedAttributes[2];
}
if (key.Equals(IdDataType)) {
return ChangedAttributes[3];
}
if (key.Equals(IdLength)) {
return ChangedAttributes[4];
}
if (key.Equals(IdDecimals)) {
return ChangedAttributes[5];
}
if (key.Equals(IdIsMandatory)) {
return ChangedAttributes[6];
}
if (key.Equals(IdIsAutoGenerated)) {
return ChangedAttributes[7];
}
if (key.Equals(IdLabel)) {
return ChangedAttributes[8];
}
if (key.Equals(IdOrderNumber)) {
return ChangedAttributes[9];
}
if (key.Equals(IdForeignKeyEntityId)) {
return ChangedAttributes[10];
}
throw new System.InvalidOperationException();
}

public bool OptimizedAttributeGet(GlobalObjectKey key) {
if (key.Equals(IdId)) {
return OptimizedAttributes[0];
}
if (key.Equals(IdName)) {
return OptimizedAttributes[1];
}
if (key.Equals(IdEntityId)) {
return OptimizedAttributes[2];
}
if (key.Equals(IdDataType)) {
return OptimizedAttributes[3];
}
if (key.Equals(IdLength)) {
return OptimizedAttributes[4];
}
if (key.Equals(IdDecimals)) {
return OptimizedAttributes[5];
}
if (key.Equals(IdIsMandatory)) {
return OptimizedAttributes[6];
}
if (key.Equals(IdIsAutoGenerated)) {
return OptimizedAttributes[7];
}
if (key.Equals(IdLabel)) {
return OptimizedAttributes[8];
}
if (key.Equals(IdOrderNumber)) {
return OptimizedAttributes[9];
}
if (key.Equals(IdForeignKeyEntityId)) {
return OptimizedAttributes[10];
}
throw new System.InvalidOperationException();
}

public object AttributeGet(GlobalObjectKey key) {
if (key == IdId) {
return ssId;
}
if (key == IdName) {
return ssName;
}
if (key == IdEntityId) {
return ssEntityId;
}
if (key == IdDataType) {
return ssDataType;
}
if (key == IdLength) {
return ssLength;
}
if (key == IdDecimals) {
return ssDecimals;
}
if (key == IdIsMandatory) {
return ssIsMandatory;
}
if (key == IdIsAutoGenerated) {
return ssIsAutoGenerated;
}
if (key == IdLabel) {
return ssLabel;
}
if (key == IdOrderNumber) {
return ssOrderNumber;
}
if (key == IdForeignKeyEntityId) {
return ssForeignKeyEntityId;
}
throw new Exception("Invalid key");
}
public object GetAttribute(Guid attributeKey) {
if (attributeKey == IdId.Key.AsGuid) {
return ssId;
}
if (attributeKey == IdName.Key.AsGuid) {
return ssName;
}
if (attributeKey == IdEntityId.Key.AsGuid) {
return ssEntityId;
}
if (attributeKey == IdDataType.Key.AsGuid) {
return ssDataType;
}
if (attributeKey == IdLength.Key.AsGuid) {
return ssLength;
}
if (attributeKey == IdDecimals.Key.AsGuid) {
return ssDecimals;
}
if (attributeKey == IdIsMandatory.Key.AsGuid) {
return ssIsMandatory;
}
if (attributeKey == IdIsAutoGenerated.Key.AsGuid) {
return ssIsAutoGenerated;
}
if (attributeKey == IdLabel.Key.AsGuid) {
return ssLabel;
}
if (attributeKey == IdOrderNumber.Key.AsGuid) {
return ssOrderNumber;
}
if (attributeKey == IdForeignKeyEntityId.Key.AsGuid) {
return ssForeignKeyEntityId;
}
throw new Exception("Invalid key");
}
public void FillFromOther(IRecord other) {
ChangedAttributes = new BitArray(11);
OptimizedAttributes = new BitArray(11);
if (other == null) return;
ssId = (string) other.AttributeGet(IdId);
ChangedAttributes[0] = other.ChangedAttributeGet(IdId);
OptimizedAttributes[0] = other.OptimizedAttributeGet(IdId);
ssName = (string) other.AttributeGet(IdName);
ChangedAttributes[1] = other.ChangedAttributeGet(IdName);
OptimizedAttributes[1] = other.OptimizedAttributeGet(IdName);
ssEntityId = (string) other.AttributeGet(IdEntityId);
ChangedAttributes[2] = other.ChangedAttributeGet(IdEntityId);
OptimizedAttributes[2] = other.OptimizedAttributeGet(IdEntityId);
ssDataType = (string) other.AttributeGet(IdDataType);
ChangedAttributes[3] = other.ChangedAttributeGet(IdDataType);
OptimizedAttributes[3] = other.OptimizedAttributeGet(IdDataType);
ssLength = (int) other.AttributeGet(IdLength);
ChangedAttributes[4] = other.ChangedAttributeGet(IdLength);
OptimizedAttributes[4] = other.OptimizedAttributeGet(IdLength);
ssDecimals = (int) other.AttributeGet(IdDecimals);
ChangedAttributes[5] = other.ChangedAttributeGet(IdDecimals);
OptimizedAttributes[5] = other.OptimizedAttributeGet(IdDecimals);
ssIsMandatory = (bool) other.AttributeGet(IdIsMandatory);
ChangedAttributes[6] = other.ChangedAttributeGet(IdIsMandatory);
OptimizedAttributes[6] = other.OptimizedAttributeGet(IdIsMandatory);
ssIsAutoGenerated = (bool) other.AttributeGet(IdIsAutoGenerated);
ChangedAttributes[7] = other.ChangedAttributeGet(IdIsAutoGenerated);
OptimizedAttributes[7] = other.OptimizedAttributeGet(IdIsAutoGenerated);
ssLabel = (string) other.AttributeGet(IdLabel);
ChangedAttributes[8] = other.ChangedAttributeGet(IdLabel);
OptimizedAttributes[8] = other.OptimizedAttributeGet(IdLabel);
ssOrderNumber = (int) other.AttributeGet(IdOrderNumber);
ChangedAttributes[9] = other.ChangedAttributeGet(IdOrderNumber);
OptimizedAttributes[9] = other.OptimizedAttributeGet(IdOrderNumber);
ssForeignKeyEntityId = (string) other.AttributeGet(IdForeignKeyEntityId);
ChangedAttributes[10] = other.ChangedAttributeGet(IdForeignKeyEntityId);
OptimizedAttributes[10] = other.OptimizedAttributeGet(IdForeignKeyEntityId);
}
} // ENEntityAttributeEntityRecord

/// <summary>
/// RecordList type <code>EntityAttributeList</code> that represents a record list of
///  <code>EntityAttribute</code>
/// </summary>
public partial class RLEntityAttributeList : GenericRecordList<ENEntityAttributeEntityRecord>, IEnumerable, IEnumerator {
public static void EnsureInitialized(){}

protected override ENEntityAttributeEntityRecord GetElementDefaultValue() {
return new ENEntityAttributeEntityRecord();
}

public T[] ToArray<T>(Func<ENEntityAttributeEntityRecord, T> converter) {
  return ToArray(this, converter);
}

public static T[] ToArray<T>(RLEntityAttributeList recordList, Func<ENEntityAttributeEntityRecord, T> converter) {
  return InnerToArray(recordList, converter);
}
public static implicit operator RLEntityAttributeList(ENEntityAttributeEntityRecord[] array) {
  RLEntityAttributeList result = new RLEntityAttributeList();
result.InnerFromArray(array);
    return result;
}

public static RLEntityAttributeList ToList<T>(T[] array, Func <T, ENEntityAttributeEntityRecord> converter) {
  RLEntityAttributeList result = new RLEntityAttributeList();
  result.InnerFromArray(array, converter);
  return result;
}

public static RLEntityAttributeList FromRestList<T>(RestList<T> restList, Func <T, ENEntityAttributeEntityRecord> converter) {
  RLEntityAttributeList result = new RLEntityAttributeList();
  result.InnerFromRestList(restList, converter);
  return result;
}
public RLEntityAttributeList() : base() {
}
public override BitArray[] GetDefaultOptimizedValues(){
BitArray[] def = new BitArray[0];
return def;
}
/// <summary>
/// Create as new list
/// </summary>
/// <returns>The new record list</returns>
protected override OSList<ENEntityAttributeEntityRecord> NewList() {
return new RLEntityAttributeList();
}


} // RLEntityAttributeList
}
