using OutSystems.RESTService.Runtime.Abstractions;
using OutSystems.RESTService.Runtime.Abstractions.Behaviors;
using System.Text.Json.Serialization;


namespace ssSystem_.RestRecords;

// EntityAttribute
public class JSONENEntityAttributeEntityRecord : AbstractRESTStructure<ENEntityAttributeEntityRecord> {
[JsonProperty("Id")]
[JsonPropertyName("Id")]
public string AttrId;

[JsonProperty("Name")]
[JsonPropertyName("Name")]
public string AttrName;

[JsonProperty("EntityId")]
[JsonPropertyName("EntityId")]
public string AttrEntityId;

[JsonProperty("DataType")]
[JsonPropertyName("DataType")]
public string AttrDataType;

[JsonProperty("Length")]
[JsonPropertyName("Length")]
public int? AttrLength;

[JsonProperty("Decimals")]
[JsonPropertyName("Decimals")]
public int? AttrDecimals;

[JsonProperty("IsMandatory")]
[JsonPropertyName("IsMandatory")]
public bool? AttrIsMandatory;

[JsonProperty("IsAutoGenerated")]
[JsonPropertyName("IsAutoGenerated")]
public bool? AttrIsAutoGenerated;

[JsonProperty("Label")]
[JsonPropertyName("Label")]
public string AttrLabel;

[JsonProperty("OrderNumber")]
[JsonPropertyName("OrderNumber")]
public int? AttrOrderNumber;

[JsonProperty("ForeignKeyEntityId")]
[JsonPropertyName("ForeignKeyEntityId")]
public string AttrForeignKeyEntityId;

public JSONENEntityAttributeEntityRecord() { }

public JSONENEntityAttributeEntityRecord (ENEntityAttributeEntityRecord s, IBehaviorsConfiguration config) {
  if (config.DefaultValuesBehavior == DefaultValuesBehavior.DontSend) { 
AttrId = s.ssId;
AttrName = s.ssName;
AttrEntityId = s.ssEntityId;
AttrDataType = s.ssDataType;
AttrLength = ConvertToRestWithoutDefaults(s.ssLength, 0);
AttrDecimals = ConvertToRestWithoutDefaults(s.ssDecimals, 0);
AttrIsMandatory = (bool?) s.ssIsMandatory;
AttrIsAutoGenerated = (bool?) s.ssIsAutoGenerated;
AttrLabel = s.ssLabel;
AttrOrderNumber = (int?) s.ssOrderNumber;
AttrForeignKeyEntityId = ConvertToRestWithoutDefaults(s.ssForeignKeyEntityId, "");
  } else {
AttrId = s.ssId;
AttrName = s.ssName;
AttrEntityId = s.ssEntityId;
AttrDataType = s.ssDataType;
AttrLength = (int?) s.ssLength;
AttrDecimals = (int?) s.ssDecimals;
AttrIsMandatory = (bool?) s.ssIsMandatory;
AttrIsAutoGenerated = (bool?) s.ssIsAutoGenerated;
AttrLabel = s.ssLabel;
AttrOrderNumber = (int?) s.ssOrderNumber;
AttrForeignKeyEntityId = s.ssForeignKeyEntityId;
  }
}

public static Func<ssSystem_.RestRecords.JSONENEntityAttributeEntityRecord, ENEntityAttributeEntityRecord> ToStructureDelegate(IBehaviorsConfiguration config) { 
  return (ssSystem_.RestRecords.JSONENEntityAttributeEntityRecord s) => ToStructure(s, config);
}
public static ENEntityAttributeEntityRecord ToStructure(ssSystem_.RestRecords.JSONENEntityAttributeEntityRecord obj, IBehaviorsConfiguration config) { 
  ENEntityAttributeEntityRecord s = new ENEntityAttributeEntityRecord();
  if(obj != null) {
  s.ssId = obj.AttrId == null ? "" : obj.AttrId;
  s.ssName = obj.AttrName == null ? "" : obj.AttrName;
  s.ssEntityId = obj.AttrEntityId == null ? "" : obj.AttrEntityId;
  s.ssDataType = obj.AttrDataType == null ? "" : obj.AttrDataType;
  s.ssLength = obj.AttrLength == null ? 0 : obj.AttrLength.Value;
  s.ssDecimals = obj.AttrDecimals == null ? 0 : obj.AttrDecimals.Value;
  s.ssIsMandatory = obj.AttrIsMandatory == null ? false : obj.AttrIsMandatory.Value;
  s.ssIsAutoGenerated = obj.AttrIsAutoGenerated == null ? false : obj.AttrIsAutoGenerated.Value;
  s.ssLabel = obj.AttrLabel == null ? "" : obj.AttrLabel;
  s.ssOrderNumber = obj.AttrOrderNumber == null ? 0 : obj.AttrOrderNumber.Value;
  s.ssForeignKeyEntityId = obj.AttrForeignKeyEntityId == null ? "" : obj.AttrForeignKeyEntityId;
  }
  return s;
}

public static Func<ENEntityAttributeEntityRecord, ssSystem_.RestRecords.JSONENEntityAttributeEntityRecord> FromStructureDelegate(IBehaviorsConfiguration config) { 
  return (ENEntityAttributeEntityRecord s) => FromStructure(s, config);
}
public static ssSystem_.RestRecords.JSONENEntityAttributeEntityRecord FromStructure(ENEntityAttributeEntityRecord s, IBehaviorsConfiguration config) { 
  return new ssSystem_.RestRecords.JSONENEntityAttributeEntityRecord(s, config);
}

}


